default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: drplisd95fg1
  username: dtuqnappgdylpp
  password: 3a8355e832bf650096ff62a83c88a0e7290c372197abef3037216e8bd96d6509
  host: ec2-23-22-156-110.compute-1.amazonaws.com
  port: 5432

test:
  <<: *default
  database: drplisd95fg1

production:
  <<: *default
  database: drplisd95fg1
  username: dtuqnappgdylpp
  password: 3a8355e832bf650096ff62a83c88a0e7290c372197abef3037216e8bd96d6509
