default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: d32s9u6f0lbmo5
  username: mytefdehhuouvc
  password: a405bb409e4f3b93cba7da10d0e2dca858208d02b4406fa2fbca0206b321a569
  host: ec2-176-34-97-213.eu-west-1.compute.amazonaws.com
  port: 5432

test:
  <<: *default
  database: d32s9u6f0lbmo5

production:
  <<: *default
  database: d32s9u6f0lbmo5
  username: mytefdehhuouvc
  password: a405bb409e4f3b93cba7da10d0e2dca858208d02b4406fa2fbca0206b321a569
